import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Search from '@/components/Search'
import Jobs from '@/components/Jobs'
import Value from '@/components/Value'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Job Search</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gradient-to-r bg-white h-screen text-gray-700'>
        <div className='w-[85%] m-auto bg-white'>
          <Navbar />
          <Search />
          <Jobs />
          <Value />
          <Footer />
        </div>
      </main>
    </>
  )
}
